version: '3.1'  # Escolha a versão adequada para o seu projeto

services:
  postgres:
    build: .
    container_name: my-folio-tracker-postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env  # Use as variáveis de ambiente do arquivo .env
